import json
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from lib.architecture_baseline import (  # noqa: E402
    _TABLE_SPECS,
    NON_ARCHITECTURE_CATEGORIES,
    compare_component_documents,
    parse_component_markdown_text,
)
from lib.architecture_merge import (  # noqa: E402
    PATCH_SCHEMA_PATH,
    load_rejected_additions,
    merge_architecture_documents,
    merge_architecture_files,
    parse_change_records,
    parse_patch_records,
)


def document(
    rows: list[tuple[str, str, str]],
    *,
    purpose: str = "Analyzer purpose.",
    data_flows: str = "Analyzer flows.",
    analysis: str = "Analyzer analysis.",
    extra: str = "",
) -> str:
    table_rows = "\n".join(
        f"| {name} | {kind} | {row_purpose} |" for name, kind, row_purpose in rows
    )
    return f"""# Component: Example

## Metadata

- **Repository**: example/example
- **Version**: abc123
- **Distribution**: rhoai
- **Languages**: Python
- **Deployment Type**: Service
- **Generated By**: arch-analyzer

## Purpose

{purpose}

## Architecture Components

| Component | Type | Purpose |
|-----------|------|---------|
{table_rows}

{extra}## APIs Exposed

### Custom Resource Definitions (CRDs)

| Group | Version | Kind | Scope | Purpose |
|-------|---------|------|-------|---------|

### HTTP Endpoints

| Path | Method | Port | Protocol | Encryption | Auth | Purpose |
|------|--------|------|----------|------------|------|---------|

### gRPC Services

| Service | Port | Protocol | Encryption | Auth | Purpose |
|---------|------|----------|------------|------|---------|

## Dependencies

### External Dependencies

| Component | Version | Required | Purpose |
|-----------|---------|----------|---------|

### Internal Platform Dependencies

| Component | Interaction Type | Purpose |
|-----------|------------------|---------|

## Network Architecture

### Services

| Service Name | Type | Port | Target Port | Protocol | Encryption | Auth | Exposure |
|--------------|------|------|-------------|----------|------------|------|----------|

### Ingress

| Name | Type | Hosts | Port | Protocol | Encryption | TLS Mode | Exposure |
|------|------|-------|------|----------|------------|----------|----------|

### Egress

| Destination | Port | Protocol | Encryption | Auth | Purpose |
|-------------|------|----------|------------|------|---------|

## Security

### RBAC - Cluster Roles

| Role Name | API Group | Resources | Verbs |
|-----------|-----------|-----------|-------|

### RBAC - Role Bindings

| Binding Name | Namespace | Role | Service Account |
|--------------|-----------|------|-----------------|

### Secrets

| Secret Name | Type | Purpose | Provisioned By | Auto-Rotate |
|-------------|------|---------|----------------|-------------|

### Authentication & Authorization

| Endpoint | Methods | Auth Mechanism | Enforcement Point | Policy |
|----------|---------|----------------|-------------------|--------|

## Data Flows

{data_flows}

## Integration Points

| Component | Interaction Type | Port | Protocol | Encryption | Purpose |
|-----------|------------------|------|----------|------------|---------|

## Architectural Analysis

{analysis}

## Recent Changes

| Version | Date | Changes |
|---------|------|---------|
"""


def change_record(*rows: tuple[str, ...]) -> str:
    body = "\n".join("| " + " | ".join(row) + " |" for row in rows)
    header = (
        "| Action | Category | Row Key | Column | Analyzer Value | "
        "Candidate Value | Reason | Evidence |"
    )
    return f"""# Architecture Change Evidence

{header}
|--------|----------|---------|--------|----------------|-----------------|--------|----------|
{body}
"""


def patch_artifact(*operations: dict[str, object]) -> str:
    return json.dumps({"schema_version": 1, "operations": list(operations)})


def test_patch_schema_covers_every_authoritative_architecture_category():
    schema = json.loads(PATCH_SCHEMA_PATH.read_text())
    schema_categories = set(
        schema["$defs"]["operation"]["properties"]["category"]["enum"]
    )
    merge_categories = {
        spec.category
        for spec in _TABLE_SPECS
        if spec.category not in NON_ARCHITECTURE_CATEGORIES
    }

    assert schema_categories == merge_categories


def add_operation(
    *,
    category: str = "architecture_components",
    key: list[str] | None = None,
    evidence: list[str] | None = None,
) -> dict[str, object]:
    return {
        "action": "add",
        "category": category,
        "key": key or ["worker"],
        "column": "*",
        "analyzer_value": None,
        "candidate_value": None,
        "reason": "Worker entry point is deployed",
        "evidence": evidence or ["worker.py:10-20"],
    }


def comparison(analyzer: str, merged: str):
    return compare_component_documents(
        parse_component_markdown_text(analyzer, path="analyzer.md"),
        parse_component_markdown_text(merged, path="merged.md"),
    )


def test_silent_row_deletion_is_restored():
    analyzer = document([("api", "Service", "API"), ("worker", "Service", "Jobs")])
    candidate = document([("api", "Service", "API")])

    result = merge_architecture_documents(analyzer, candidate)

    assert "| worker | Service | Jobs |" in result.text
    assert any(
        item.status == "restored" and item.action == "delete"
        for item in result.decisions
    )
    assert comparison(analyzer, result.text).structured_row_recall == 1.0


def test_silent_cell_rewrite_is_restored():
    analyzer = document([("api", "Service", "API")])
    candidate = document([("api", "Library", "API")])

    result = merge_architecture_documents(analyzer, candidate)

    assert "| api | Service | API |" in result.text
    assert result.counts["restored"] == 1
    assert comparison(analyzer, result.text).conflict_count == 0


def test_duplicate_row_keys_are_paired_by_exact_content():
    analyzer = document(
        [
            ("gateway", "HTTPRoute", "External ingress"),
            ("gateway", "HTTPRoute", "Platform ingress"),
        ]
    )
    candidate = document(
        [
            ("gateway", "HTTPRoute", "Platform ingress"),
            ("gateway", "HTTPRoute", "External ingress"),
        ]
    )

    result = merge_architecture_documents(analyzer, candidate)

    assert result.counts["restored"] == 0
    assert result.counts["rejected"] == 0
    assert result.unchanged_by_category["architecture_components"] == 2
    assert comparison(analyzer, result.text).structured_row_recall == 1.0


def test_unsupported_candidate_row_is_rejected():
    analyzer = document([("api", "Service", "API")])
    candidate = document([("api", "Service", "API"), ("worker", "Service", "Jobs")])

    result = merge_architecture_documents(analyzer, candidate)

    assert "| worker | Service | Jobs |" not in result.text
    assert any(
        item.status == "rejected" and item.key == ("worker",)
        for item in result.decisions
    )


def test_evidence_backed_row_addition_is_applied():
    analyzer = document([("api", "Service", "API")])
    candidate = document([("api", "Service", "API"), ("worker", "Service", "Jobs")])
    changes = change_record(
        (
            "add",
            "architecture_components",
            "worker",
            "*",
            "<empty>",
            "<empty>",
            "Worker entry point is deployed",
            "worker.py:10-20",
        )
    )

    result = merge_architecture_documents(analyzer, candidate, changes_text=changes)

    assert "| worker | Service | Jobs |" in result.text
    assert result.counts["applied"] == 1
    assert comparison(analyzer, result.text).structured_row_recall == 1.0


def test_json_patch_row_addition_is_applied():
    analyzer = document([("api", "Service", "API")])
    candidate = document([("api", "Service", "API"), ("worker", "Service", "Jobs")])

    result = merge_architecture_documents(
        analyzer,
        candidate,
        patch_text=patch_artifact(add_operation()),
    )

    assert "| worker | Service | Jobs |" in result.text
    assert result.counts["applied"] == 1
    assert result.parse_errors == []
    assert result.change_artifact_format == "architecture-table-patch/v1"


def test_json_patch_cell_update_requires_exact_values():
    analyzer = document([("api", "Service", "API")])
    candidate = document([("api", "Library", "API")])
    operation = {
        "action": "update",
        "category": "architecture_components",
        "key": ["api"],
        "column": "type",
        "analyzer_value": "Service",
        "candidate_value": "Library",
        "reason": "The entry point is imported rather than deployed",
        "evidence": ["src/api.py:4-18"],
    }

    result = merge_architecture_documents(
        analyzer,
        candidate,
        patch_text=patch_artifact(operation),
    )

    assert "| api | Library | API |" in result.text
    assert result.counts["applied"] == 1
    assert result.counts["restored"] == 0


def test_json_patch_mismatched_cell_values_are_validation_errors():
    analyzer = document([("api", "Service", "API")])
    candidate = document([("api", "Library", "API")])
    operation = {
        "action": "update",
        "category": "architecture_components",
        "key": ["api"],
        "column": "type",
        "analyzer_value": "Wrong old value",
        "candidate_value": "Library",
        "reason": "The entry point is imported rather than deployed",
        "evidence": ["src/api.py:4-18"],
    }

    result = merge_architecture_documents(
        analyzer,
        candidate,
        patch_text=patch_artifact(operation),
    )

    assert "| api | Service | API |" in result.text
    assert result.counts["restored"] == 1
    assert any(
        "no exact candidate/analyzer change" in error
        for error in result.parse_errors
    )


@pytest.mark.parametrize(
    ("operation", "message"),
    [
        (
            add_operation(category="metadata"),
            "is not one of",
        ),
        (
            add_operation(category="authentication", key=["HTTP API"]),
            "is too short",
        ),
        (
            add_operation(evidence=["src/api.py"]),
            "does not match",
        ),
    ],
)
def test_json_patch_schema_errors_are_actionable(
    operation: dict[str, object], message: str
):
    records, errors = parse_patch_records(patch_artifact(operation))

    assert records == []
    assert any("$.operations[0]" in error and message in error for error in errors)


def test_json_patch_rejects_duplicate_operation_identity():
    operation = add_operation()

    records, errors = parse_patch_records(patch_artifact(operation, operation))

    assert len(records) == 1
    assert any("duplicate operation identity" in error for error in errors)


def test_json_patch_rejects_placeholder_reason_and_reversed_evidence_range():
    operation = add_operation(evidence=["worker.py:20-10"])
    operation["reason"] = "N/A"

    records, errors = parse_patch_records(patch_artifact(operation))

    assert records == []
    assert any("reason must explain" in error for error in errors)
    assert any("evidence range is reversed" in error for error in errors)


def test_json_patch_add_requires_null_cell_values():
    operation = add_operation()
    operation["candidate_value"] = "Service row"

    records, errors = parse_patch_records(patch_artifact(operation))

    assert records == []
    assert any("$.operations[0].candidate_value" in error for error in errors)
    assert any("is not of type 'null'" in error for error in errors)


def test_json_patch_rejects_category_outside_readiness_budget():
    analyzer = document([("api", "Service", "API")])
    candidate = document([("api", "Service", "API"), ("worker", "Service", "Jobs")])

    result = merge_architecture_documents(
        analyzer,
        candidate,
        patch_text=patch_artifact(add_operation()),
        allowed_change_categories=("authentication",),
    )

    assert "| worker | Service | Jobs |" not in result.text
    assert any(
        "outside the readiness gap budget" in error
        for error in result.parse_errors
    )


def test_json_patch_and_legacy_change_record_cannot_be_combined():
    analyzer = document([("api", "Service", "API")])
    candidate = document([("api", "Service", "API")])

    result = merge_architecture_documents(
        analyzer,
        candidate,
        patch_text=patch_artifact(),
        changes_text=change_record(),
    )

    assert result.change_artifact_format == "conflicting"
    assert result.parse_errors == [
        "provide one structured-change artifact: JSON patch or legacy Markdown"
    ]


def test_invalid_json_patch_fails_before_writing_final_merge(tmp_path: Path):
    analyzer = tmp_path / "analyzer.md"
    candidate = tmp_path / "candidate.md"
    patch = tmp_path / "patch.json"
    output = tmp_path / "merged.md"
    report = tmp_path / "merge.json"
    analyzer.write_text(document([("api", "Service", "API")]))
    candidate.write_text(
        document([("api", "Service", "API"), ("worker", "Service", "Jobs")])
    )
    patch.write_text(patch_artifact(add_operation(evidence=["worker.py"])))

    with pytest.raises(ValueError, match="architecture patch validation failed"):
        merge_architecture_files(
            analyzer,
            candidate,
            output,
            patch=patch,
            report_json=report,
        )

    assert not output.exists()
    assert "$.operations[0]" in report.read_text()


def test_source_adjudicated_addition_is_rejected():
    analyzer = document([("api", "Service", "API")])
    candidate = document([("api", "Service", "API"), ("worker", "Service", "Jobs")])
    changes = change_record(
        (
            "add",
            "architecture_components",
            "worker",
            "*",
            "<empty>",
            "<empty>",
            "Worker entry point is deployed",
            "worker.py:10-20",
        )
    )

    result = merge_architecture_documents(
        analyzer,
        candidate,
        changes_text=changes,
        rejected_additions={
            ("architecture_components", ("worker",)): (
                "The worker is test-only",
                ("tests/worker.py:4-12",),
            )
        },
    )

    assert "| worker | Service | Jobs |" not in result.text
    rejected = [
        decision
        for decision in result.decisions
        if decision.status == "rejected" and decision.key == ("worker",)
    ]
    assert len(rejected) == 1
    assert rejected[0].reason == "The worker is test-only"
    assert rejected[0].evidence == ("tests/worker.py:4-12",)


def test_rejected_addition_loader_normalizes_persisted_row_keys(tmp_path: Path):
    adjudications = tmp_path / "adjudications.json"
    adjudications.write_text(
        json.dumps(
            {
                "accepted_analyzer_absences": [
                    {
                        "component": "example",
                        "category": "architecture_components",
                        "key": [" Batch-Apiserver "],
                        "reason": "The build artifact has a more precise name.",
                        "evidence": ["Dockerfile:20"],
                    }
                ]
            }
        )
    )

    rejected = load_rejected_additions("example", path=adjudications)

    assert rejected == {
        ("architecture_components", ("batch-apiserver",)): (
            "The build artifact has a more precise name.",
            ("Dockerfile:20",),
        )
    }


def test_evidence_backed_row_deletion_is_applied():
    analyzer = document([("api", "Service", "API"), ("worker", "Service", "Jobs")])
    candidate = document([("api", "Service", "API")])
    changes = change_record(
        (
            "delete",
            "architecture_components",
            "worker",
            "*",
            "<empty>",
            "<empty>",
            "Worker is test-only and not deployed",
            "tests/worker.py:10-20",
        )
    )

    result = merge_architecture_documents(analyzer, candidate, changes_text=changes)

    assert "| worker | Service | Jobs |" not in result.text
    assert any(
        item.status == "applied" and item.action == "delete"
        for item in result.decisions
    )


def test_evidence_backed_cell_correction_is_applied_and_adjudicated():
    analyzer = document([("api", "Service", "API")])
    candidate = document([("api", "Library", "API")])
    changes = change_record(
        (
            "update",
            "architecture_components",
            "api",
            "type",
            "Service",
            "Library",
            "Source defines a reusable package",
            "src/api.py:3-18",
        )
    )

    result = merge_architecture_documents(analyzer, candidate, changes_text=changes)

    assert "| api | Library | API |" in result.text
    assert result.counts["applied"] == 1
    assert result.accepted_conflicts == [
        {
            "category": "architecture_components",
            "key": ["api"],
            "column": "type",
            "analyzer": "Service",
            "generated": "Library",
            "reason": "Source defines a reusable package",
            "evidence": ["src/api.py:3-18"],
        }
    ]
    assert "## Source References" not in result.text
    assert result.decisions[0].evidence == ("src/api.py:3-18",)


def test_evidence_backed_row_deletion_is_adjudicated():
    analyzer = document([("api", "Service", "API")])
    candidate = document([])
    changes = change_record(
        (
            "delete",
            "architecture_components",
            "api",
            "*",
            "",
            "",
            "Source only defines a client",
            "src/client.py:3-18",
        )
    )

    result = merge_architecture_documents(analyzer, candidate, changes_text=changes)

    assert result.accepted_deletions == [
        {
            "category": "architecture_components",
            "key": ["api"],
            "reason": "Source only defines a client",
            "evidence": ["src/client.py:3-18"],
        }
    ]


def test_synthesis_and_conditional_sections_are_agent_owned():
    analyzer = document([("api", "Service", "API")])
    conditional = """## AIPCC Ecosystems Use

No AIPCC base image is used (`Dockerfile.konflux:1-20`).

"""
    candidate = document(
        [("api", "Service", "API")],
        purpose="Agent purpose.",
        data_flows="Agent flows.",
        analysis="Agent analysis.",
        extra=conditional,
    )

    result = merge_architecture_documents(analyzer, candidate)

    assert "Agent purpose." in result.text
    assert "Agent flows." in result.text
    assert "Agent analysis." in result.text
    assert "## AIPCC Ecosystems Use" in result.text


def test_security_conditional_subsection_is_merged():
    analyzer = document([("api", "Service", "API")])
    candidate = document([("api", "Service", "API")]).replace(
        "## Data Flows",
        "### FIPS Compliance\n\n"
        "Uses the system crypto policy (`security.go:12-20`).\n\n"
        "## Data Flows",
    )

    result = merge_architecture_documents(analyzer, candidate)

    assert "### FIPS Compliance" in result.text
    assert "Uses the system crypto policy" in result.text


def test_malformed_or_stale_change_record_is_rejected():
    analyzer = document([("api", "Service", "API")])
    candidate = document([("api", "Library", "API")])
    malformed = change_record(
        (
            "update",
            "architecture_components",
            "api",
            "type",
            "Wrong old value",
            "Library",
            "Correction",
            "not-a-line-reference",
        )
    )

    result = merge_architecture_documents(analyzer, candidate, changes_text=malformed)

    assert "| api | Service | API |" in result.text
    assert result.parse_errors
    assert result.counts["restored"] == 1


def test_change_record_parser_requires_exact_category_key_shape():
    records, errors = parse_change_records(
        change_record(
            (
                "update",
                "http_endpoints",
                "GET",
                "protocol",
                "HTTP",
                "HTTPS",
                "TLS termination is in-process",
                "app.py:42",
            )
        )
    )

    assert records == []
    assert any("row key needs at least 2 value(s)" in error for error in errors)


def test_authentication_change_record_key_uses_endpoint_and_methods():
    records, errors = parse_change_records(
        change_record(
            (
                "add",
                "authentication",
                "Tracking Server API :: All",
                "*",
                "<empty>",
                "<empty>",
                "RHOAI deployment loads the authentication plugin",
                "Dockerfile.konflux:80",
            )
        )
    )

    assert errors == []
    assert records[0].key == ("tracking server api", "all")


def test_authentication_row_key_migration_uses_delete_and_add_records():
    analyzer = document([("api", "Service", "API")]).replace(
        "| Endpoint | Methods | Auth Mechanism | Enforcement Point | Policy |\n"
        "|----------|---------|----------------|-------------------|--------|",
        "| Endpoint | Methods | Auth Mechanism | Enforcement Point | Policy |\n"
        "|----------|---------|----------------|-------------------|--------|\n"
        "| HTTP API | All | None | FastAPI | No auth |",
    )
    candidate = analyzer.replace(
        "| HTTP API | All | None | FastAPI | No auth |",
        (
            "| Tracking Server API | All | kubernetes-auth plugin | Flask entry "
            "point | "
            "External policy |\n"
            "| Gateway API | All | None | FastAPI | No middleware |"
        ),
    )
    changes = change_record(
        (
            "delete",
            "authentication",
            "HTTP API :: All",
            "*",
            "<empty>",
            "<empty>",
            (
                "The combined analyzer surface is split into source-backed serving "
                "surfaces"
            ),
            "Dockerfile.konflux:80",
        ),
        (
            "add",
            "authentication",
            "Tracking Server API :: All",
            "*",
            "<empty>",
            "<empty>",
            "The tracking server loads the authentication plugin",
            "Dockerfile.konflux:80",
        ),
        (
            "add",
            "authentication",
            "Gateway API :: All",
            "*",
            "<empty>",
            "<empty>",
            "The gateway is a separate unauthenticated surface",
            "mlflow/gateway/app.py:301",
        ),
    )

    result = merge_architecture_documents(analyzer, candidate, changes_text=changes)

    assert "| HTTP API | All | None | FastAPI | No auth |" not in result.text
    assert (
        "| Tracking Server API | All | kubernetes-auth plugin | Flask entry point | "
        "External policy |"
    ) in result.text
    assert "| Gateway API | All | None | FastAPI | No middleware |" in result.text
    assert result.counts["applied"] == 3
    assert result.counts["rejected"] == 0
    assert result.counts["restored"] == 0


def test_placeholder_addition_is_not_treated_as_an_architecture_fact():
    analyzer = document([("api", "Service", "API")])
    candidate = analyzer.replace(
        "| Component | Interaction Type | Purpose |\n"
        "|-----------|------------------|---------|",
        "| Component | Interaction Type | Purpose |\n"
        "|-----------|------------------|---------|\n"
        "| None identified | N/A | No dependency found |",
    )
    changes = change_record(
        (
            "add",
            "internal_dependencies",
            "None identified",
            "*",
            "<empty>",
            "<empty>",
            "No dependency import found",
            "src/main.go:1-20",
        )
    )

    result = merge_architecture_documents(
        analyzer,
        candidate,
        changes_text=changes,
        allowed_change_categories=("internal_dependencies",),
    )

    assert "| None identified |" not in result.text
    assert any("concrete architecture fact" in error for error in result.parse_errors)


def test_change_record_parser_adapts_trailing_non_key_cells():
    records, errors = parse_change_records(
        change_record(
            (
                "add",
                "internal_dependencies",
                "TGIS :: gRPC client",
                "*",
                "<empty>",
                "<empty>",
                "TGIS is the inference backend",
                "backend.py:201-223",
            )
        )
    )

    assert errors == []
    assert records[0].key == ("tgis",)


def test_change_record_parser_accepts_inline_code_evidence():
    records, errors = parse_change_records(
        change_record(
            (
                "update",
                "architecture_components",
                "api",
                "purpose",
                "API",
                "Public API",
                "Handler proves the public API",
                "`app.py:42-48`, `routes.py:10`",
            )
        )
    )

    assert errors == []
    assert records[0].evidence == ("app.py:42-48", "routes.py:10")


def test_change_record_parser_accepts_tables_without_outer_pipes():
    change_text = "\n".join(
        [
            "# Architecture Change Evidence",
            "",
            "Action | Category | Row Key | Column | Analyzer Value | Candidate Value | "
            "Reason | Evidence",
            "---|---|---|---|---|---|---|---",
            "add | architecture_components | worker | * | <empty> | <empty> | "
            "Worker is deployed | worker.py:10",
        ]
    )
    records, errors = parse_change_records(change_text)

    assert errors == []
    assert records[0].key == ("worker",)


def test_change_record_parser_expands_same_file_line_shorthand():
    records, errors = parse_change_records(
        change_record(
            (
                "update",
                "architecture_components",
                "api",
                "purpose",
                "API",
                "Public API",
                "Handler proves the public API",
                "app.py:39-51,258",
            )
        )
    )

    assert errors == []
    assert records[0].evidence == ("app.py:39-51", "app.py:258")


def test_readiness_budget_rejects_change_outside_allowed_categories():
    analyzer = document([("api", "Service", "API")])
    candidate = document([("api", "Service", "API"), ("worker", "Service", "Jobs")])
    changes = change_record(
        (
            "add",
            "architecture_components",
            "worker",
            "*",
            "<empty>",
            "<empty>",
            "Worker is deployed",
            "worker.py:10",
        )
    )

    result = merge_architecture_documents(
        analyzer,
        candidate,
        changes_text=changes,
        allowed_change_categories=("http_endpoints",),
    )

    assert "| worker | Service | Jobs |" not in result.text
    assert any(
        "outside the readiness gap budget" in error for error in result.parse_errors
    )


@pytest.mark.parametrize(
    ("action", "analyzer_value", "candidate_value", "evidence", "message"),
    [
        ("add", "unexpected", "<empty>", "worker.py:10", "requires Analyzer"),
        ("delete", "<empty>", "unexpected", "worker.py:10", "requires Analyzer"),
        ("add", "<empty>", "<empty>", "/tmp/worker.py:10", "repository-relative"),
        ("add", "<empty>", "<empty>", "../worker.py:10", "repository-relative"),
        ("add", "<empty>", "<empty>", "worker.py:20-10", "range is reversed"),
    ],
)
def test_change_record_parser_rejects_invalid_row_evidence(
    action: str,
    analyzer_value: str,
    candidate_value: str,
    evidence: str,
    message: str,
):
    records, errors = parse_change_records(
        change_record(
            (
                action,
                "architecture_components",
                "worker",
                "*",
                analyzer_value,
                candidate_value,
                "Worker evidence",
                evidence,
            )
        )
    )

    assert records == []
    assert any(message in error for error in errors)


@pytest.mark.parametrize(
    ("component", "expected"), [("MLServer", 37), ("notebooks", 32)]
)
def test_pilot_change_records_remain_parseable(component: str, expected: int):
    change_path = (
        PROJECT_ROOT / "tests/fixtures/architecture_merge" / f"{component}.changes.md"
    )

    records, errors = parse_change_records(change_path.read_text())

    assert errors == []
    assert len(records) == expected


def test_odh_gitops_json_patch_replay_preserves_valid_candidate_rows(
    tmp_path: Path,
):
    fixture = (
        PROJECT_ROOT / "tests/fixtures/architecture_patch/odh_gitops"
    )
    output = tmp_path / "merged.md"

    result = merge_architecture_files(
        fixture / "analyzer.md",
        fixture / "candidate.md",
        output,
        patch=fixture / "patch.json",
        component="odh-gitops",
        allowed_change_categories=(
            "architecture_components",
            "internal_dependencies",
            "authentication",
            "integration_points",
        ),
    )

    assert result.parse_errors == []
    assert result.counts["applied"] == 5
    assert result.counts["rejected"] == 0
    assert result.counts["restored"] == 0
    merged = output.read_text()
    assert "| rhai-on-openshift-chart | Helm Chart |" in merged
    assert "| Kueue Operator | OLM Subscription / Helm |" in merged
    assert "| Platform Services | All | Authorino |" in merged
    assert "| Authorino | CRD Configuration |" in merged
