"""Tests for surface planning and promoted-document coverage validation."""

from __future__ import annotations

import copy
import json
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from lib.architecture_surface_coverage import (  # noqa: E402
    SCHEMA_VERSION,
    build_surface_inventory,
    finalized_sidecar,
    validate_surface_coverage,
)
from lib.phases.architecture import _validate_generated_architecture  # noqa: E402


def _operator_analyzer() -> dict:
    return {
        "entrypoints": [
            {
                "name": "manager",
                "type": "Go controller-runtime operator",
                "source": "cmd/main.go:301",
            }
        ],
        "services": [
            {
                "name": "controller-manager-metrics-service",
                "source": "config/metrics-service.yaml:3",
            }
        ],
        "deployments": [
            {
                "name": "manager",
                "source": "config/manager.yaml:1",
                "args": ["--metrics-secure=true"],
            },
            {
                "name": "gateway-oidc-proxy",
                "source": "config/gateway-oidc.yaml:1",
            },
        ],
        "controller_watches": [
            {
                "type": "Watches",
                "gvk": "/v1/Namespace",
                "controller": "auth.ServiceHandler",
                "source": "internal/controller/auth/controller.go:63",
            }
        ],
        "runtime_webhook_servers": [
            {
                "name": "admission",
                "source": "internal/webhook/server.go:44",
            }
        ],
        "runtime_clients": [
            {
                "target": "Kubernetes API",
                "source": "internal/client/client.go:20",
            }
        ],
        "security_evidence": [
            {
                "kind": "tls-config",
                "detail": "crypto/tls configuration",
                "source": "cmd/main.go:478",
            }
        ],
        "category_coverage": {
            "fips_compliance": {
                "status": "partial",
                "limitations": ["runtime FIPS posture is not verified"],
            }
        },
    }


def _document(
    auth_row: bool, *, auth_mechanism: str = "controller-runtime filter"
) -> str:
    row = ""
    if auth_row:
        row = (
            f"| Operator metrics | HTTPS | {auth_mechanism} | "
            "metrics server | Conditional on secure serving |\n"
        )
    return f"""# Component: example

## Security

### Authentication & Authorization

| Endpoint | Methods | Auth Mechanism | Enforcement Point | Policy |
|----------|---------|----------------|-------------------|--------|
{row}
## Architectural Analysis

The component uses conditional metrics authentication when secure serving is enabled.
"""


def _structurally_valid_document() -> str:
    return """# Component: example

## Metadata
- **Repository**: example/example
- **Version**: abc123
- **Distribution**: rhoai
- **Languages**: Go
- **Deployment Type**: Operator
- **Generated By**: test

## Purpose
Test component.

## Architectural Analysis
The component exposes a controller-runtime manager.

## Architecture Components
No components identified.

## APIs Exposed

### Custom Resource Definitions (CRDs)
None identified.

### HTTP Endpoints
None identified.

### gRPC Services
None identified.

## Dependencies

### External Dependencies
None identified.

### Internal Platform Dependencies
None identified.

## Network Architecture

### Services
None identified.

### Ingress
None identified.

### Egress
None identified.

## Security

### RBAC - Cluster Roles
None identified.

### RBAC - Role Bindings
None identified.

### Secrets
None identified.

### Authentication & Authorization
None identified.

## Data Flows
No flow established.

## Integration Points
None identified.

## Recent Changes
None identified.
"""


def _write_document(tmp_path: Path, name: str, *, auth_row: bool) -> Path:
    path = tmp_path / name
    path.write_text(_document(auth_row))
    return path


def _metrics_inventory() -> dict:
    inventory = build_surface_inventory(
        _operator_analyzer(), component="example"
    )
    inventory["surfaces"] = [
        surface
        for surface in inventory["surfaces"]
        if surface["id"] == "authentication.metrics-enforcement"
    ]
    inventory["summary"] = {
        "seeded": 1,
        "documented": 0,
        "unresolved": 1,
        "not_applicable": 0,
    }
    return inventory


def test_operator_inventory_uses_specific_evidence_nominated_surfaces() -> None:
    inventory = build_surface_inventory(
        _operator_analyzer(), component="example-operator"
    )

    assert inventory["schema_version"] == SCHEMA_VERSION
    assert inventory["component_roles"] == ["operator"]
    identifiers = {surface["id"] for surface in inventory["surfaces"]}
    assert identifiers == {
        "authentication.admission-serving-identity",
        "authentication.gateway-modes",
        "authentication.metrics-enforcement",
        "compliance.runtime-fips",
        "controller.named-resource-watches",
        "dependencies.outbound-credentials",
        "lifecycle.configuration-tls",
    }
    assert all(
        surface["candidate_locations"] for surface in inventory["surfaces"]
    )


def test_metrics_surface_is_uncertain_and_excludes_gateway_proxy() -> None:
    role_only = build_surface_inventory(
        {
            "entrypoints": [
                {
                    "name": "manager",
                    "type": "Go controller-runtime operator",
                    "source": "cmd/main.go:10",
                }
            ]
        },
        component="minimal-operator",
    )
    role_surface = next(
        item
        for item in role_only["surfaces"]
        if item["id"] == "authentication.metrics-enforcement"
    )
    assert role_surface["applicability"]["status"] == "uncertain"
    assert role_surface["candidate_locations"] == []

    fixture = json.loads(
        (
            PROJECT_ROOT
            / "tests/fixtures/architecture_surface_coverage/rhods_operator"
            / "analyzer_metrics_characteristics.json"
        ).read_text()
    )
    actual_shape = build_surface_inventory(fixture, component="rhods-operator")
    actual_surface = next(
        item
        for item in actual_shape["surfaces"]
        if item["id"] == "authentication.metrics-enforcement"
    )
    assert actual_surface["applicability"]["status"] == "applicable"
    assert {item["path"] for item in actual_surface["candidate_locations"]} == {
        "config/default/manager_webhook_patch.yaml",
        "config/default/metrics_service_patch.yaml",
    }
    assert not any(
        "gateway" in item["path"]
        for item in actual_surface["candidate_locations"]
    )


def test_behavioral_facts_nominate_exact_surface_ranges() -> None:
    analyzer = {
        "entrypoints": [
            {
                "name": "manager",
                "type": "Go controller-runtime operator",
                "source": "cmd/main.go:301",
            }
        ],
        "behavioral_evidence": [
            {
                "kind": "conditional-metrics-enforcement",
                "status": "observed",
                "identity": "controller-runtime metrics",
                "serving_surface": "controller-runtime metrics serving surface",
                "configuration_branch": "oconfig.MetricsSecure is true",
                "enforcement_provider": (
                    "filters.WithAuthenticationAndAuthorization"
                ),
                "source": "cmd/main.go:485-500",
            },
            {
                "kind": "named-watch-predicate",
                "status": "observed",
                "identity": (
                    "internal/controller/services/auth.ServiceHandler"
                ),
                "watched_gvk": "/v1/Namespace",
                "literal_values": ["models-as-a-service"],
                "source": (
                    "internal/controller/services/auth/auth_controller.go:63-69"
                ),
            },
            {
                "kind": "named-watch-predicate",
                "status": "unresolved",
                "identity": "internal/controller/other.Handler",
                "watched_gvk": "apiextensions.k8s.io/v1/CustomResourceDefinition",
                "source": "internal/controller/other/controller.go:20-25",
                "limitations": ["unsupported predicate wrapper"],
            },
        ],
    }

    inventory = build_surface_inventory(analyzer, component="rhods-operator")
    surfaces = {surface["id"]: surface for surface in inventory["surfaces"]}

    assert surfaces["authentication.metrics-enforcement"][
        "candidate_locations"
    ] == [
        {
            "path": "cmd/main.go",
            "line_range": "485-500",
            "origin": "analyzer",
        }
    ]
    assert surfaces["controller.named-resource-watches"][
        "candidate_locations"
    ] == [
        {
            "path": (
                "internal/controller/services/auth/auth_controller.go"
            ),
            "line_range": "63-69",
            "origin": "analyzer",
        }
    ]


def test_behavioral_analyzer_fact_can_support_documented_surface(
    tmp_path: Path,
) -> None:
    analyzer = {
        "entrypoints": [
            {
                "name": "manager",
                "type": "Go controller-runtime operator",
                "source": "cmd/main.go:301",
            }
        ],
        "behavioral_evidence": [
            {
                "kind": "conditional-metrics-enforcement",
                "status": "observed",
                "identity": "controller-runtime metrics",
                "serving_surface": "controller-runtime metrics serving surface",
                "configuration_branch": "oconfig.MetricsSecure is true",
                "enforcement_provider": (
                    "filters.WithAuthenticationAndAuthorization"
                ),
                "source": "cmd/main.go:485-500",
            }
        ],
    }
    inventory = build_surface_inventory(analyzer, component="rhods-operator")
    inventory["surfaces"] = [
        surface
        for surface in inventory["surfaces"]
        if surface["id"] == "authentication.metrics-enforcement"
    ]
    sidecar = copy.deepcopy(inventory)
    sidecar["surfaces"][0].update(
        {
            "disposition": "documented",
            "evidence_status": "available",
            "claim_support": "supported",
            "evidence": [
                {
                    "kind": "analyzer-fact",
                    "reference": (
                        "component-architecture.json#/behavioral_evidence/0"
                    ),
                }
            ],
            "document_reference": {
                "kind": "section",
                "section": "Architectural Analysis",
                "fact_identity": "conditional metrics authentication",
            },
        }
    )
    document = _write_document(tmp_path, "final.md", auth_row=True)

    report = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        promoted_document=document,
        analyzer_document=analyzer,
        observed_reads=[],
    )

    assert report["structural_valid"] is True
    assert report["summary"]["documented"] == 1
    assert report["validator_findings"] == []


def test_role_rules_do_not_apply_operator_surface_to_service_or_manifest() -> None:
    service = build_surface_inventory(
        {
            "entrypoints": [
                {
                    "name": "api",
                    "type": "Go service",
                    "source": "cmd/api/main.go:10",
                }
            ],
            "http_endpoints": [
                {"path": "/v1/items", "source": "internal/api/routes.go:20"}
            ],
        },
        component="api",
    )
    manifest = build_surface_inventory(
        {
            "deployments": [
                {"name": "worker", "source": "deploy/worker.yaml:1"}
            ],
            "services": [
                {"name": "worker", "source": "deploy/service.yaml:1"}
            ],
            "secrets_referenced": [
                {"name": "worker-token", "source": "deploy/worker.yaml:20"}
            ],
        },
        component="worker-chart",
    )

    assert service["component_roles"] == ["service"]
    assert {item["id"] for item in service["surfaces"]} == {
        "authentication.service-endpoints"
    }
    assert manifest["component_roles"] == ["manifest"]
    assert {item["id"] for item in manifest["surfaces"]} == {
        "network.workload-exposure",
        "security.credential-wiring",
    }


def test_representative_corpus_uses_the_same_role_rules() -> None:
    fixture_root = (
        PROJECT_ROOT / "tests/fixtures/architecture_surface_coverage"
    )
    corpus = json.loads((fixture_root / "corpus.json").read_text())
    inventories = {}
    for member in corpus["members"]:
        analyzer_fixture = member.get("analyzer_fixture")
        if analyzer_fixture is None:
            continue
        analyzer = json.loads((fixture_root / analyzer_fixture).read_text())
        inventories[member["id"]] = build_surface_inventory(
            analyzer, component=member["id"]
        )

    service_ids = {
        item["id"] for item in inventories["example-api"]["surfaces"]
    }
    manifest_ids = {
        item["id"] for item in inventories["example-chart"]["surfaces"]
    }
    assert service_ids == {"authentication.service-endpoints"}
    assert manifest_ids == {
        "network.workload-exposure",
        "security.credential-wiring",
    }


def test_validator_distinguishes_unavailable_omitted_and_explicit_unresolved(
    tmp_path: Path,
) -> None:
    inventory = _metrics_inventory()
    final = _write_document(tmp_path, "final.md", auth_row=False)

    unavailable = copy.deepcopy(inventory)
    unavailable["surfaces"][0]["evidence_status"] = "unavailable"
    unavailable_report = validate_surface_coverage(
        inventory=inventory,
        sidecar=unavailable,
        promoted_document=final,
    )
    assert [
        item["classification"]
        for item in unavailable_report["validator_findings"]
    ] == ["extraction_gap"]

    omitted = copy.deepcopy(inventory)
    omitted["surfaces"][0]["evidence_status"] = "available"
    omitted["surfaces"][0]["evidence"] = [
        {"kind": "source-read", "reference": "cmd/main.go:480-500"}
    ]
    omitted_report = validate_surface_coverage(
        inventory=inventory,
        sidecar=omitted,
        promoted_document=final,
    )
    assert [
        item["classification"]
        for item in omitted_report["validator_findings"]
    ] == ["synthesis_omission"]

    explicit = copy.deepcopy(inventory)
    uninspected_report = validate_surface_coverage(
        inventory=inventory,
        sidecar=explicit,
        promoted_document=final,
    )
    assert [
        item["classification"]
        for item in uninspected_report["validator_findings"]
    ] == ["inspection_gap"]

    explicit_report = validate_surface_coverage(
        inventory=inventory,
        sidecar=explicit,
        promoted_document=final,
        observed_reads=[
            {
                "path": "config/metrics-service.yaml",
                "line_range": "1-20",
                "outcome": "partially-resolved",
            }
        ],
    )
    assert explicit_report["validator_findings"] == []
    assert explicit_report["summary"]["unresolved"] == 1
    assert explicit_report["unresolved_safety_critical_surfaces"] == [
        "authentication.metrics-enforcement"
    ]


def test_structurally_valid_document_can_receive_specific_coverage_warning(
    tmp_path: Path,
) -> None:
    inventory = _metrics_inventory()
    document = tmp_path / "valid.md"
    document.write_text(_structurally_valid_document())
    _validate_generated_architecture(document)

    report = validate_surface_coverage(
        inventory=inventory,
        sidecar=copy.deepcopy(inventory),
        promoted_document=document,
    )

    assert report["structural_valid"] is True
    assert report["validator_findings"] == [
        {
            "classification": "inspection_gap",
            "surface_id": "authentication.metrics-enforcement",
            "message": (
                "candidate inspection cannot be verified because source-read "
                "observation is unavailable"
            ),
        }
    ]


def test_documented_claim_stronger_than_evidence_is_unverifiable(
    tmp_path: Path,
) -> None:
    inventory = _metrics_inventory()
    sidecar = copy.deepcopy(inventory)
    surface = sidecar["surfaces"][0]
    surface.update(
        {
            "disposition": "documented",
            "evidence_status": "available",
            "claim_support": "unsupported",
            "evidence": [
                {
                    "kind": "source-candidate",
                    "reference": "config/metrics-service.yaml:3",
                }
            ],
            "remaining_question": "",
            "document_reference": {
                "kind": "section",
                "section": "Architectural Analysis",
                "fact_identity": "conditional metrics authentication",
            },
        }
    )
    final = _write_document(tmp_path, "final.md", auth_row=False)

    report = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        promoted_document=final,
    )

    assert report["structural_valid"] is False
    assert {
        item["classification"] for item in report["validator_findings"]
    } == {"inspection_gap", "unverifiable_coverage_claim"}
    recovered = finalized_sidecar(sidecar, report, inventory=inventory)
    assert recovered["surfaces"][0]["disposition"] == "unresolved"
    assert recovered["observed_reads"] == []


def test_seeded_source_candidate_is_not_proof_without_read_or_fact(
    tmp_path: Path,
) -> None:
    inventory = _metrics_inventory()
    sidecar = copy.deepcopy(inventory)
    surface = sidecar["surfaces"][0]
    surface.update(
        {
            "disposition": "documented",
            "evidence_status": "available",
            "claim_support": "supported",
            "evidence": [
                {
                    "kind": "source-candidate",
                    "reference": "config/metrics-service.yaml:3",
                }
            ],
            "document_reference": {
                "kind": "table-row",
                "category": "authentication",
                "row_key": ["Operator metrics", "HTTPS"],
                "expected_cells": {
                    "auth_mechanism": "controller-runtime filter"
                },
            },
        }
    )
    final = _write_document(tmp_path, "final.md", auth_row=True)

    report = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        promoted_document=final,
        observed_reads=[],
    )

    assert report["status"] == "warning"
    assert report["structural_valid"] is False
    assert report["summary"]["documented"] == 0
    assert report["summary"]["unresolved"] == 1
    assert any(
        "independently verified evidence" in error
        for error in report["structural_errors"]
    )


def test_evidence_backed_not_applicable_is_valid(tmp_path: Path) -> None:
    inventory = _metrics_inventory()
    sidecar = copy.deepcopy(inventory)
    surface = sidecar["surfaces"][0]
    surface["disposition"] = "not-applicable"
    surface["evidence_status"] = "available"
    surface["claim_support"] = "supported"
    surface["applicability"] = {
        "status": "not-applicable",
        "basis": surface["applicability"]["basis"],
        "evidence": ["component-architecture.json#/entrypoints"],
    }
    surface["evidence"] = [
        {
            "kind": "analyzer-fact",
            "reference": "component-architecture.json#/entrypoints",
        }
    ]
    final = _write_document(tmp_path, "final.md", auth_row=False)

    report = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        promoted_document=final,
        analyzer_document=_operator_analyzer(),
    )

    assert report["status"] == "pass"
    assert report["summary"]["not_applicable"] == 1


def test_rejected_candidate_fact_is_reported_as_merge_loss(
    tmp_path: Path,
) -> None:
    inventory = _metrics_inventory()
    sidecar = copy.deepcopy(inventory)
    surface = sidecar["surfaces"][0]
    surface.update(
        {
            "disposition": "documented",
            "evidence_status": "available",
            "claim_support": "supported",
            "evidence": [
                {
                    "kind": "source-read",
                    "reference": "config/metrics-service.yaml:3",
                }
            ],
            "document_reference": {
                "kind": "table-row",
                "category": "authentication",
                "row_key": ["Operator metrics", "HTTPS"],
                "expected_cells": {
                    "auth_mechanism": "controller-runtime filter"
                },
            },
        }
    )
    candidate = _write_document(tmp_path, "candidate.md", auth_row=True)
    final = tmp_path / "final.md"
    final.write_text(
        _document(auth_row=True, auth_mechanism="legacy token proxy")
    )

    report = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        candidate_document=candidate,
        promoted_document=final,
        observed_reads=[
            {"path": "config/metrics-service.yaml", "line_range": "3"}
        ],
    )

    assert [
        item["classification"] for item in report["validator_findings"]
    ] == ["merge_loss"]


def test_missing_and_duplicate_seeded_records_are_structural_errors(
    tmp_path: Path,
) -> None:
    inventory = _metrics_inventory()
    sidecar = copy.deepcopy(inventory)
    sidecar["surfaces"].append(copy.deepcopy(sidecar["surfaces"][0]))
    final = _write_document(tmp_path, "final.md", auth_row=False)

    duplicate = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        promoted_document=final,
    )
    missing = validate_surface_coverage(
        inventory=inventory,
        sidecar={**inventory, "surfaces": []},
        promoted_document=final,
    )

    assert duplicate["structural_valid"] is False
    assert duplicate["coverage_accounting"]["duplicates"] == [
        "authentication.metrics-enforcement"
    ]
    assert missing["structural_valid"] is False
    assert missing["coverage_accounting"]["missing"] == [
        "authentication.metrics-enforcement"
    ]


def test_missing_and_invalid_sidecars_preserve_seeded_safety_accounting(
    tmp_path: Path,
) -> None:
    inventory = _metrics_inventory()
    final = _write_document(tmp_path, "final.md", auth_row=False)

    missing = validate_surface_coverage(
        inventory=inventory,
        sidecar=None,
        promoted_document=final,
    )
    invalid_sidecar = copy.deepcopy(inventory)
    invalid_sidecar["surfaces"][0]["priority"] = "optional"
    invalid = validate_surface_coverage(
        inventory=inventory,
        sidecar=invalid_sidecar,
        promoted_document=final,
    )

    for report in (missing, invalid):
        assert report["structural_valid"] is False
        assert report["summary"] == {
            "seeded": 1,
            "documented": 0,
            "unresolved": 1,
            "not_applicable": 0,
        }
        assert report["unresolved_safety_critical_surfaces"] == [
            "authentication.metrics-enforcement"
        ]
        assert report["accounted_surfaces"][0] == inventory["surfaces"][0]
        assert any(
            item["surface_id"] == "authentication.metrics-enforcement"
            for item in report["validator_findings"]
        )
    recovered = finalized_sidecar(None, missing, inventory=inventory)
    assert recovered["surfaces"] == inventory["surfaces"]
    assert recovered["summary"]["unresolved"] == 1


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("parent_category", "integration_points"),
        ("component_role", "service"),
        ("question", "A replacement question?"),
        ("priority", "normal"),
        ("candidate_locations", [{"path": "other.go", "line_range": "1"}]),
    ],
)
def test_seeded_surface_fields_are_immutable(
    tmp_path: Path, field: str, value: object
) -> None:
    inventory = _metrics_inventory()
    sidecar = copy.deepcopy(inventory)
    sidecar["surfaces"][0][field] = value

    report = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        promoted_document=_write_document(tmp_path, "final.md", auth_row=False),
    )

    assert report["structural_valid"] is False
    assert any(
        f"seeded {field} is immutable" in error
        for error in report["structural_errors"]
    )
    assert report["summary"]["unresolved"] == 1


def test_seeded_roles_and_applicability_basis_are_immutable(tmp_path: Path) -> None:
    inventory = _metrics_inventory()
    sidecar = copy.deepcopy(inventory)
    sidecar["component_roles"] = ["service"]
    sidecar["surfaces"][0]["applicability"]["basis"] = "agent replacement"

    report = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        promoted_document=_write_document(tmp_path, "final.md", auth_row=False),
    )

    assert report["structural_valid"] is False
    assert "component_roles must match the seeded inventory" in report[
        "structural_errors"
    ]
    assert any(
        "seeded applicability basis is immutable" in error
        for error in report["structural_errors"]
    )


@pytest.mark.parametrize(
    "reference",
    ["/etc/passwd:1", "../other/repo.go:1", "cmd/main.go:not-a-line"],
)
def test_source_evidence_requires_safe_exact_path_reference(
    tmp_path: Path, reference: str
) -> None:
    inventory = _metrics_inventory()
    sidecar = copy.deepcopy(inventory)
    surface = sidecar["surfaces"][0]
    surface.update(
        {
            "evidence_status": "available",
            "claim_support": "supported",
            "evidence": [{"kind": "source-read", "reference": reference}],
        }
    )

    report = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        promoted_document=_write_document(tmp_path, "final.md", auth_row=False),
    )

    assert report["structural_valid"] is False


def test_not_applicable_rejects_candidate_assertion_and_bad_analyzer_pointer(
    tmp_path: Path,
) -> None:
    inventory = _metrics_inventory()
    final = _write_document(tmp_path, "final.md", auth_row=False)

    candidate_only = copy.deepcopy(inventory)
    candidate_surface = candidate_only["surfaces"][0]
    candidate_surface.update(
        {
            "disposition": "not-applicable",
            "evidence_status": "available",
            "claim_support": "supported",
            "evidence": [
                {
                    "kind": "source-candidate",
                    "reference": "config/metrics-service.yaml:3",
                }
            ],
        }
    )
    candidate_surface["applicability"] = {
        **candidate_surface["applicability"],
        "status": "not-applicable",
        "evidence": ["config/metrics-service.yaml:3"],
    }
    missing_pointer = copy.deepcopy(candidate_only)
    pointer_surface = missing_pointer["surfaces"][0]
    pointer_surface["evidence"] = [
        {
            "kind": "analyzer-fact",
            "reference": "component-architecture.json#/does-not-exist",
        }
    ]
    pointer_surface["applicability"]["evidence"] = [
        "component-architecture.json#/does-not-exist"
    ]

    candidate_report = validate_surface_coverage(
        inventory=inventory,
        sidecar=candidate_only,
        promoted_document=final,
        analyzer_document=_operator_analyzer(),
    )
    pointer_report = validate_surface_coverage(
        inventory=inventory,
        sidecar=missing_pointer,
        promoted_document=final,
        analyzer_document=_operator_analyzer(),
    )

    assert candidate_report["structural_valid"] is False
    assert pointer_report["structural_valid"] is False
    assert any(
        "JSON pointer does not exist" in error
        for error in pointer_report["structural_errors"]
    )


def test_evidence_status_and_claim_support_must_be_consistent(tmp_path: Path) -> None:
    inventory = _metrics_inventory()
    sidecar = copy.deepcopy(inventory)
    sidecar["surfaces"][0]["claim_support"] = "supported"

    report = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        promoted_document=_write_document(tmp_path, "final.md", auth_row=False),
    )

    assert report["structural_valid"] is False
    assert any(
        "requires available evidence" in error
        for error in report["structural_errors"]
    )


def test_agent_observation_claim_cannot_suppress_inspection_gap(tmp_path: Path) -> None:
    inventory = _metrics_inventory()
    sidecar = copy.deepcopy(inventory)
    sidecar["observed_reads"] = [
        {
            "path": "config/metrics-service.yaml",
            "line_range": "1-20",
            "outcome": "agent-claimed",
        }
    ]
    sidecar["surfaces"][0].update(
        {
            "disposition": "documented",
            "evidence_status": "available",
            "claim_support": "supported",
            "evidence": [
                {
                    "kind": "analyzer-fact",
                    "reference": "component-architecture.json#/entrypoints",
                }
            ],
            "document_reference": {
                "kind": "section",
                "section": "Architectural Analysis",
                "fact_identity": "conditional metrics authentication",
            },
        }
    )

    report = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        promoted_document=_write_document(tmp_path, "final.md", auth_row=False),
        observed_reads=[],
        analyzer_document=_operator_analyzer(),
    )

    assert report["structural_valid"] is False
    assert report["observed_reads"] == []
    assert report["summary"]["documented"] == 0
    assert report["summary"]["unresolved"] == 1
    assert report["unresolved_safety_critical_surfaces"] == [
        "authentication.metrics-enforcement"
    ]
    assert {
        item["classification"] for item in report["validator_findings"]
    } == {"inspection_gap", "unverifiable_coverage_claim"}


def test_additional_discovered_surface_id_is_allowed(tmp_path: Path) -> None:
    inventory = _metrics_inventory()
    sidecar = copy.deepcopy(inventory)
    discovered = copy.deepcopy(sidecar["surfaces"][0])
    discovered.update(
        {
            "id": "security.discovered-boundary",
            "parent_category": "authentication",
            "question": "What additional boundary was discovered?",
            "candidate_locations": [],
            "remaining_question": "What additional boundary was discovered?",
        }
    )
    discovered["applicability"] = {
        "status": "uncertain",
        "basis": "Discovered during bounded inspection.",
        "evidence": [],
    }
    sidecar["surfaces"].append(discovered)

    report = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        promoted_document=_write_document(tmp_path, "final.md", auth_row=False),
        observed_reads=[],
    )

    assert report["structural_valid"] is True
    assert report["coverage_accounting"]["seeded"] == 1
    assert len(report["accounted_surfaces"]) == 2


def test_existing_source_and_line_bounds_are_validated(tmp_path: Path) -> None:
    checkout = tmp_path / "checkout"
    source = checkout / "cmd/main.go"
    source.parent.mkdir(parents=True)
    source.write_text("one\ntwo\nthree\n")
    inventory = _metrics_inventory()
    sidecar = copy.deepcopy(inventory)
    sidecar["surfaces"][0].update(
        {
            "evidence_status": "available",
            "claim_support": "supported",
            "evidence": [
                {"kind": "source-read", "reference": "cmd/main.go:2-8"}
            ],
        }
    )

    report = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        promoted_document=_write_document(tmp_path, "final.md", auth_row=False),
        observed_reads=[{"path": "cmd/main.go"}],
        source_root=checkout,
    )

    assert report["structural_valid"] is False
    assert any(
        "line range exceeds the file" in error
        for error in report["structural_errors"]
    )


def test_applicability_evidence_must_match_top_level_evidence(tmp_path: Path) -> None:
    inventory = _metrics_inventory()
    sidecar = copy.deepcopy(inventory)
    surface = sidecar["surfaces"][0]
    surface.update(
        {
            "disposition": "not-applicable",
            "evidence_status": "available",
            "claim_support": "supported",
            "evidence": [
                {
                    "kind": "analyzer-fact",
                    "reference": "component-architecture.json#/entrypoints",
                }
            ],
        }
    )
    surface["applicability"] = {
        **surface["applicability"],
        "status": "not-applicable",
        "evidence": ["component-architecture.json#/services"],
    }

    report = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        promoted_document=_write_document(tmp_path, "final.md", auth_row=False),
        analyzer_document=_operator_analyzer(),
    )

    assert report["structural_valid"] is False
    assert any(
        "must reference top-level evidence" in error
        for error in report["structural_errors"]
    )


def test_bounded_source_evidence_requires_full_observed_range(tmp_path: Path) -> None:
    inventory = _metrics_inventory()
    inventory["surfaces"][0]["candidate_locations"] = [
        {"path": "cmd/main.go", "line_range": "480-500", "origin": "analyzer"}
    ]
    sidecar = copy.deepcopy(inventory)
    sidecar["surfaces"][0].update(
        {
            "disposition": "documented",
            "evidence_status": "available",
            "claim_support": "supported",
            "evidence": [
                {"kind": "source-read", "reference": "cmd/main.go:480-500"}
            ],
            "document_reference": {
                "kind": "table-row",
                "category": "authentication",
                "row_key": ["Operator metrics", "HTTPS"],
                "expected_cells": {
                    "auth_mechanism": "controller-runtime filter"
                },
            },
        }
    )
    final = _write_document(tmp_path, "final.md", auth_row=True)

    far = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        promoted_document=final,
        observed_reads=[{"path": "cmd/main.go", "line_range": "1-10"}],
    )
    partial = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        promoted_document=final,
        observed_reads=[{"path": "cmd/main.go", "line_range": "490-510"}],
    )
    covered = validate_surface_coverage(
        inventory=inventory,
        sidecar=sidecar,
        promoted_document=final,
        observed_reads=[{"path": "cmd/main.go", "line_range": "480-unknown"}],
    )

    for report in (far, partial):
        assert report["structural_valid"] is False
        assert report["summary"]["documented"] == 0
        assert report["summary"]["unresolved"] == 1
    assert covered["status"] == "pass"
    assert covered["summary"]["documented"] == 1


def test_candidate_inspection_requires_overlap_and_known_start(tmp_path: Path) -> None:
    inventory = _metrics_inventory()
    inventory["surfaces"][0]["candidate_locations"] = [
        {"path": "cmd/main.go", "line_range": "480-500", "origin": "analyzer"}
    ]
    final = _write_document(tmp_path, "final.md", auth_row=False)

    def findings(line_range: str) -> list[str]:
        report = validate_surface_coverage(
            inventory=inventory,
            sidecar=copy.deepcopy(inventory),
            promoted_document=final,
            observed_reads=[
                {"path": "cmd/main.go", "line_range": line_range}
            ],
        )
        return [
            item["classification"] for item in report["validator_findings"]
        ]

    assert findings("1-10") == ["inspection_gap"]
    assert findings("unknown") == ["inspection_gap"]
    assert findings("490-510") == []
    assert findings("480-unknown") == []


def test_path_pattern_counts_only_matching_observed_telemetry(tmp_path: Path) -> None:
    inventory = _metrics_inventory()
    inventory["surfaces"][0]["candidate_locations"] = [
        {
            "path_pattern": "**/*clusterserviceversion*.yaml",
            "origin": "role-rule",
        }
    ]
    final = _write_document(tmp_path, "final.md", auth_row=False)

    missed = validate_surface_coverage(
        inventory=inventory,
        sidecar=copy.deepcopy(inventory),
        promoted_document=final,
        observed_reads=[
            {"path": "config/manager.yaml", "line_range": "1-unknown"}
        ],
    )
    inspected = validate_surface_coverage(
        inventory=inventory,
        sidecar=copy.deepcopy(inventory),
        promoted_document=final,
        observed_reads=[
            {
                "path": "config/rhoai/manifests/bases/"
                "rhods-operator.clusterserviceversion.yaml",
                "line_range": "1-unknown",
            }
        ],
    )

    assert [item["classification"] for item in missed["validator_findings"]] == [
        "inspection_gap"
    ]
    assert inspected["validator_findings"] == []
