package cmd

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/jctanner/arch-analyzer/internal/extractor"
	"github.com/jctanner/arch-analyzer/internal/model"
	"github.com/jctanner/arch-analyzer/internal/normalize"
	"github.com/jctanner/arch-analyzer/internal/proposal"
	"github.com/jctanner/arch-analyzer/internal/renderer"
	"github.com/jctanner/arch-analyzer/internal/schema"
	"github.com/jctanner/arch-analyzer/internal/structured"
)

func Execute(args []string) error {
	if len(args) == 0 {
		return errors.New(usage())
	}
	switch args[0] {
	case "extract":
		return extract(args[1:])
	case "render":
		return render(args[1:])
	case "normalize":
		return normalizeStructured(args[1:])
	case "render-document":
		return renderStructured(args[1:])
	case "extract-schema":
		return extractSchema(args[1:])
	case "harvest-proposals":
		return harvestProposals(args[1:])
	case "help", "-h", "--help":
		fmt.Println(usage())
		return nil
	default:
		return fmt.Errorf("unknown command %q\n\n%s", args[0], usage())
	}
}

type repeatedFlag []string

func (values *repeatedFlag) String() string { return strings.Join(*values, ",") }
func (values *repeatedFlag) Set(value string) error {
	*values = append(*values, value)
	return nil
}

func normalizeStructured(args []string) error {
	flags := flag.NewFlagSet("normalize", flag.ContinueOnError)
	inputPath := flags.String("input", "", "analyzer JSON input path")
	outputPath := flags.String("output", "", "accepted document JSON output path (stdout when omitted)")
	distribution := flags.String("distribution", "Both", "ODH, RHOAI, or Both")
	generatedBy := flags.String("generated-by", "arch-analyzer", "Generated By metadata value")
	componentMapPath := flags.String("component-map", "", "component-map.json path for canonical identity and repo lineage")
	componentMapID := flags.String("component-map-id", "component-map", "trusted identifier for the parent-supplied component-map input")
	versionScope := flags.String("version-scope", "unknown", "release/version scope, or unknown")
	integrationStatus := flags.String("integration-status", "unknown", "current, planned, not-integrated, or unknown")
	sectionsPath := flags.String("sections", "", "optional typed structured-sections JSON array")
	reuseRecordPath := flags.String("reuse-record", "", "optional trusted verified-reuse record JSON")
	sectionOriginKind := flags.String("section-origin-kind", "", "trusted section origin kind: model, human-correction, or overlay")
	sectionOriginID := flags.String("section-origin-id", "", "trusted section origin identifier")
	sectionClaimClass := flags.String("section-claim-class", "", "trusted section claim class: implementation, support, planned, or correction")
	aliasesValue := flags.String("aliases", "", "comma-separated canonical aliases")
	var patchPaths repeatedFlag
	flags.Var(&patchPaths, "patch", "untrusted typed structured patch proposal JSON path (repeatable)")
	var policyPaths repeatedFlag
	flags.Var(&policyPaths, "assembly-policy", "trusted assembly policy JSON path (repeatable; required for proposals with operations)")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if *inputPath == "" || flags.NArg() != 0 {
		return errors.New("normalize requires --input")
	}

	inputFile, err := os.Open(*inputPath)
	if err != nil {
		return fmt.Errorf("open analyzer input: %w", err)
	}
	defer inputFile.Close()

	var componentMap *model.ComponentMap
	if *componentMapPath != "" {
		componentMap, err = loadComponentMap(*componentMapPath)
		if err != nil {
			return fmt.Errorf("load component-map: %w", err)
		}
	}
	var sections []model.StructuredSection
	if *sectionsPath != "" {
		data, readErr := os.ReadFile(*sectionsPath)
		if readErr != nil {
			return fmt.Errorf("read structured sections: %w", readErr)
		}
		var inputs []structuredSectionInput
		decoder := json.NewDecoder(strings.NewReader(string(data)))
		decoder.DisallowUnknownFields()
		if decodeErr := decoder.Decode(&inputs); decodeErr != nil {
			return fmt.Errorf("decode structured sections: %w", decodeErr)
		}
		var trailing any
		if decodeErr := decoder.Decode(&trailing); !errors.Is(decodeErr, io.EOF) {
			if decodeErr == nil {
				return errors.New("decode structured sections: unexpected trailing JSON value")
			}
			return fmt.Errorf("decode structured sections: %w", decodeErr)
		}
		if len(inputs) > 0 && (strings.TrimSpace(*sectionOriginKind) == "" || strings.TrimSpace(*sectionOriginID) == "" || strings.TrimSpace(*sectionClaimClass) == "") {
			return errors.New("non-empty --sections requires trusted --section-origin-kind, --section-origin-id, and --section-claim-class")
		}
		sections = make([]model.StructuredSection, 0, len(inputs))
		for _, input := range inputs {
			sections = append(sections, model.StructuredSection{
				ID: input.ID, Status: input.Status, Blocks: input.Blocks,
				Evidence: input.Evidence, Uncertainty: input.Uncertainty,
				Authority: model.StructuredAuthority{Kind: *sectionOriginKind, Origin: *sectionOriginID, ClaimClass: *sectionClaimClass},
			})
		}
	}
	patches := make([]structured.PatchSet, 0, len(patchPaths))
	for _, path := range patchPaths {
		patchFile, openErr := os.Open(path)
		if openErr != nil {
			return fmt.Errorf("open structured patch %s: %w", path, openErr)
		}
		patch, decodeErr := structured.DecodePatch(patchFile)
		closeErr := patchFile.Close()
		if decodeErr != nil {
			return fmt.Errorf("decode structured patch %s: %w", path, decodeErr)
		}
		if closeErr != nil {
			return fmt.Errorf("close structured patch %s: %w", path, closeErr)
		}
		patches = append(patches, patch)
	}
	policies := make([]structured.AssemblyPolicy, 0, len(policyPaths))
	for _, path := range policyPaths {
		policyFile, openErr := os.Open(path)
		if openErr != nil {
			return fmt.Errorf("open structured assembly policy %s: %w", path, openErr)
		}
		policy, decodeErr := structured.DecodeAssemblyPolicy(policyFile)
		closeErr := policyFile.Close()
		if decodeErr != nil {
			return fmt.Errorf("decode structured assembly policy %s: %w", path, decodeErr)
		}
		if closeErr != nil {
			return fmt.Errorf("close structured assembly policy %s: %w", path, closeErr)
		}
		policies = append(policies, policy)
	}
	aliases := []string{}
	for _, alias := range strings.Split(*aliasesValue, ",") {
		if alias = strings.TrimSpace(alias); alias != "" {
			aliases = append(aliases, alias)
		}
	}
	var reuseRecord *structured.ReuseRecord
	if *reuseRecordPath != "" {
		data, readErr := os.ReadFile(*reuseRecordPath)
		if readErr != nil {
			return fmt.Errorf("read reuse record: %w", readErr)
		}
		var value structured.ReuseRecord
		decoder := json.NewDecoder(strings.NewReader(string(data)))
		decoder.DisallowUnknownFields()
		if decodeErr := decoder.Decode(&value); decodeErr != nil {
			return fmt.Errorf("decode reuse record: %w", decodeErr)
		}
		var trailing any
		if decodeErr := decoder.Decode(&trailing); !errors.Is(decodeErr, io.EOF) {
			if decodeErr == nil {
				return errors.New("decode reuse record: unexpected trailing JSON value")
			}
			return fmt.Errorf("decode reuse record: %w", decodeErr)
		}
		reuseRecord = &value
	}
	document, err := structured.Normalize(inputFile, structured.Options{
		Distribution: *distribution, GeneratedBy: *generatedBy,
		VersionScope: *versionScope, IntegrationStatus: *integrationStatus,
		Aliases: aliases, ComponentMap: componentMap, ComponentMapID: *componentMapID,
		Sections: sections, Patches: patches, AssemblyPolicies: policies,
		Reuse: reuseRecord,
	})
	if err != nil {
		return fmt.Errorf("normalize accepted document: %w", err)
	}
	output := os.Stdout
	if *outputPath != "" {
		output, err = os.Create(*outputPath)
		if err != nil {
			return fmt.Errorf("create accepted document output: %w", err)
		}
		defer output.Close()
	}
	return structured.Encode(output, document)
}

// structuredSectionInput is intentionally missing authority fields. Section
// content may be model-produced, while attribution is supplied separately by
// the trusted orchestrator/CLI invocation.
type structuredSectionInput struct {
	ID          string                         `json:"id"`
	Status      string                         `json:"status"`
	Blocks      []model.StructuredContentBlock `json:"blocks"`
	Evidence    []model.StructuredEvidenceRef  `json:"evidence"`
	Uncertainty string                         `json:"uncertainty,omitempty"`
}

func renderStructured(args []string) error {
	flags := flag.NewFlagSet("render-document", flag.ContinueOnError)
	inputPath := flags.String("input", "", "accepted document JSON input path")
	outputPath := flags.String("output", "", "Markdown output path (stdout when omitted)")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if *inputPath == "" || flags.NArg() != 0 {
		return errors.New("render-document requires --input")
	}
	inputFile, err := os.Open(*inputPath)
	if err != nil {
		return fmt.Errorf("open accepted document: %w", err)
	}
	defer inputFile.Close()
	document, err := structured.Decode(inputFile)
	if err != nil {
		return err
	}
	output := os.Stdout
	if *outputPath != "" {
		output, err = os.Create(*outputPath)
		if err != nil {
			return fmt.Errorf("create Markdown output: %w", err)
		}
		defer output.Close()
	}
	if err := renderer.AcceptedMarkdown(output, document); err != nil {
		return fmt.Errorf("render accepted document Markdown: %w", err)
	}
	return nil
}

func extractSchema(args []string) error {
	flags := flag.NewFlagSet("extract-schema", flag.ContinueOnError)
	outputDirectory := flags.String("output-dir", "contracts/schemas", "CRD JSON schema output directory")
	repository := ""
	flagArgs := args
	if len(args) > 0 && !strings.HasPrefix(args[0], "-") {
		repository = args[0]
		flagArgs = args[1:]
	}
	if err := flags.Parse(flagArgs); err != nil {
		return err
	}
	if repository == "" && flags.NArg() == 1 {
		repository = flags.Arg(0)
	}
	if repository == "" || flags.NArg() > 1 {
		return errors.New("extract-schema requires exactly one repository path")
	}
	count, err := schema.Extract(repository, *outputDirectory)
	if err != nil {
		return fmt.Errorf("extract CRD schemas: %w", err)
	}
	fmt.Printf("Extracted %d CRD schemas\n", count)
	return nil
}

func extract(args []string) error {
	flags := flag.NewFlagSet("extract", flag.ContinueOnError)
	outputPath := flags.String("output", "", "component-architecture.json output path (stdout when omitted)")
	distribution := flags.String("distribution", "", "overlay distribution to select, such as rhoai.next")
	overlay := flags.String("overlay", "", "explicit kustomization directory, relative to the repository")
	supplementalAuthPath := flags.String("supplemental-auth", "", "JSON file with supplemental AuthenticationFact records")
	repository := ""
	flagArgs := args
	if len(args) > 0 && !strings.HasPrefix(args[0], "-") {
		repository = args[0]
		flagArgs = args[1:]
	}
	if err := flags.Parse(flagArgs); err != nil {
		return err
	}
	extraArguments := flags.NArg()
	if repository == "" && extraArguments == 1 {
		repository = flags.Arg(0)
		extraArguments = 0
	}
	if repository == "" || extraArguments != 0 {
		return errors.New("extract requires exactly one repository path")
	}

	var supplementalAuth []model.AuthenticationFact
	if *supplementalAuthPath != "" {
		data, err := os.ReadFile(*supplementalAuthPath)
		if err != nil {
			return fmt.Errorf("read supplemental auth: %w", err)
		}
		if err := json.Unmarshal(data, &supplementalAuth); err != nil {
			return fmt.Errorf("parse supplemental auth: %w", err)
		}
	}

	input, err := extractor.Extract(repository, extractor.Options{
		Distribution:     *distribution,
		Overlay:          *overlay,
		SupplementalAuth: supplementalAuth,
	})
	if err != nil {
		return fmt.Errorf("extract architecture: %w", err)
	}

	output := os.Stdout
	if *outputPath != "" {
		output, err = os.Create(*outputPath)
		if err != nil {
			return fmt.Errorf("create output: %w", err)
		}
		defer output.Close()
	}
	return model.EncodeInput(output, input)
}

func render(args []string) error {
	flags := flag.NewFlagSet("render", flag.ContinueOnError)
	inputPath := flags.String("input", "", "component-architecture.json input path")
	outputPath := flags.String("output", "", "Markdown output path (stdout when omitted)")
	distribution := flags.String("distribution", "Both", "ODH, RHOAI, or Both")
	generatedBy := flags.String("generated-by", "arch-analyzer", "Generated By metadata value")
	componentMapPath := flags.String("component-map", "", "component-map.json path for repo lineage provenance")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if *inputPath == "" {
		return errors.New("render requires --input")
	}

	inputFile, err := os.Open(*inputPath)
	if err != nil {
		return fmt.Errorf("open input: %w", err)
	}
	defer inputFile.Close()

	input, err := model.DecodeInput(inputFile)
	if err != nil {
		return err
	}

	var componentMap *model.ComponentMap
	if *componentMapPath != "" {
		componentMap, err = loadComponentMap(*componentMapPath)
		if err != nil {
			return fmt.Errorf("load component-map: %w", err)
		}
	}

	document := normalize.Input(input, normalize.Options{
		Distribution: *distribution,
		GeneratedBy:  *generatedBy,
		ComponentMap: componentMap,
	})

	output := os.Stdout
	if *outputPath != "" {
		output, err = os.Create(*outputPath)
		if err != nil {
			return fmt.Errorf("create output: %w", err)
		}
		defer output.Close()
	}
	if err := renderer.Markdown(output, document); err != nil {
		return fmt.Errorf("render Markdown: %w", err)
	}
	if *outputPath != "" {
		contextPath := filepath.Join(filepath.Dir(*outputPath), "analyzer_synthesis_context.md")
		contextOutput, contextErr := os.Create(contextPath)
		if contextErr != nil {
			return fmt.Errorf("create analyzer synthesis context: %w", contextErr)
		}
		if contextErr = renderer.SynthesisEvidenceMarkdown(contextOutput, input); contextErr != nil {
			_ = contextOutput.Close()
			return fmt.Errorf("render analyzer synthesis context: %w", contextErr)
		}
		if contextErr = contextOutput.Close(); contextErr != nil {
			return fmt.Errorf("close analyzer synthesis context: %w", contextErr)
		}
	}
	return nil
}

func harvestProposals(args []string) error {
	flags := flag.NewFlagSet("harvest-proposals", flag.ContinueOnError)
	outputPath := flags.String("output", "", "proposal JSON output path (stdout when omitted)")
	createdDate := flags.String("created-date", "", "proposal created_date in YYYY-MM-DD format (required)")
	author := flags.String("author", "unknown", "proposal author identity")
	generatedAt := flags.String("generated-at", "", "generated_at timestamp for the proposal set envelope")
	inputPath := ""
	flagArgs := args
	if len(args) > 0 && !strings.HasPrefix(args[0], "-") {
		inputPath = args[0]
		flagArgs = args[1:]
	}
	if err := flags.Parse(flagArgs); err != nil {
		return err
	}
	if inputPath == "" && flags.NArg() == 1 {
		inputPath = flags.Arg(0)
	}
	if inputPath == "" || flags.NArg() > 1 {
		return errors.New("harvest-proposals requires exactly one YAML input path")
	}
	if *createdDate == "" {
		return errors.New("harvest-proposals requires --created-date in YYYY-MM-DD format")
	}
	if _, err := parseDate(*createdDate); err != nil {
		return fmt.Errorf("invalid --created-date %q: must be YYYY-MM-DD", *createdDate)
	}

	f, err := os.Open(inputPath)
	if err != nil {
		return fmt.Errorf("open input: %w", err)
	}
	defer f.Close()

	result, err := proposal.Harvest(f, inputPath, *author, *createdDate)
	if err != nil {
		return fmt.Errorf("harvest proposals: %w", err)
	}

	ps := result.ToProposalSet(*generatedAt)
	data, err := proposal.EncodeProposalSet(ps)
	if err != nil {
		return fmt.Errorf("encode proposals: %w", err)
	}

	output := os.Stdout
	if *outputPath != "" {
		output, err = os.Create(*outputPath)
		if err != nil {
			return fmt.Errorf("create output: %w", err)
		}
		defer output.Close()
	}
	_, err = output.Write(data)
	if err != nil {
		return fmt.Errorf("write output: %w", err)
	}
	if *outputPath != "" {
		fmt.Fprintf(os.Stderr, "Harvested %d proposals from %d qualifying records (%d total)\n",
			len(ps.Proposals), result.FilteredRecords, result.TotalRecords)
	}
	return nil
}

func parseDate(s string) (string, error) {
	if len(s) != 10 || s[4] != '-' || s[7] != '-' {
		return "", fmt.Errorf("not YYYY-MM-DD")
	}
	for i, c := range s {
		if i == 4 || i == 7 {
			continue
		}
		if c < '0' || c > '9' {
			return "", fmt.Errorf("not YYYY-MM-DD")
		}
	}
	return s, nil
}

func loadComponentMap(path string) (*model.ComponentMap, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read component-map: %w", err)
	}
	var componentMap model.ComponentMap
	if err := json.Unmarshal(data, &componentMap); err != nil {
		return nil, fmt.Errorf("parse component-map: %w", err)
	}
	return &componentMap, nil
}

func usage() string {
	return `Usage:
  arch-analyzer extract <repository> [--distribution rhoai.next] [--overlay path] [--output component-architecture.json] [--supplemental-auth facts.json]
  arch-analyzer extract-schema <repository> [--output-dir contracts/schemas]
  arch-analyzer render --input component-architecture.json [--output GENERATED_ARCHITECTURE.md] [--component-map component-map.json]
  arch-analyzer normalize --input analyzer.json [--output document.json] [--component-map component-map.json] [--sections sections.json --section-origin-kind model --section-origin-id response-01 --section-claim-class implementation] [--patch proposal.json --assembly-policy policy.json] [--reuse-record reuse.json]
  arch-analyzer render-document --input document.json [--output COMPONENT.md]
  arch-analyzer harvest-proposals <staff-corrections.yaml> --created-date YYYY-MM-DD [--author name] [--generated-at timestamp] [--output proposals.json]

Commands:
  extract            Resolve manifests and emit architecture compatibility JSON
  extract-schema     Extract CRD OpenAPI schemas as JSON Schema files
  render             Normalize analyzer JSON and render canonical component Markdown
  normalize          Normalize analyzer JSON into the accepted structured document
  render-document    Render Markdown from an accepted structured document only
  harvest-proposals  Parse staff-corrections YAML and emit pending correction proposals
  help               Show this help`
}
